import type { IFood } from "@/types/general";
import { mockCategories } from "./category";

const getRandomCategory = () => {
  const randomIndex = Math.floor(Math.random() * mockCategories.length);
  return mockCategories[randomIndex];
};

export const foods: IFood[] = [
  {
    foodId: "1",
    name: "Margherita Pizza",
    amount: 12.99,
    image: "https://cb.scene7.com/is/image/Crate/frame-margherita-pizza-1?wid=800&qlt=70&op_sharpen=1",
    description: "Classic Italian pizza topped with fresh mozzarella, tomatoes, and basil.",
    category: getRandomCategory(),
    isVisible: true,
  },
  {
    foodId: "2",
    name: "Veggie Burger",
    amount: 9.49,
    image: "https://www.realsimple.com/thmb/z3cQCYXTyDQS9ddsqqlTVE8fnpc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/real-simple-mushroom-black-bean-burgers-recipe-0c365277d4294e6db2daa3353d6ff605.jpg",
    description: "Healthy burger made with a mix of fresh vegetables and spices.",
    category: getRandomCategory(),
    isVisible: true,
  },
  {
    foodId: "3",
    name: "Caesar Salad",
    amount: 7.99,
    image: "https://cdn.loveandlemons.com/wp-content/uploads/2024/12/caesar-salad.jpg",
    description: "Crisp romaine lettuce with Caesar dressing, croutons, and parmesan.",
    category: getRandomCategory(),
    isVisible: true,
  },
  {
    foodId: "4",
    name: "Grilled Sandwich",
    amount: 8.99,
    image: "https://www.vegrecipesofindia.com/wp-content/uploads/2014/01/grilled-sandwich-4.jpg",
    description: "Toasted sandwich filled with fresh vegetables and cheese.",
    category: getRandomCategory(),
    isVisible: false,
  },
  {
    foodId: "5",
    name: "Pasta Alfredo",
    amount: 11.49,
    image: "https://s3.amazonaws.com/static.realcaliforniamilk.com/media/recipes_2/fettuccine-alfredo-with-creme-fraiche.jpg",
    description: "Creamy Alfredo pasta made with rich cheese sauce and fettuccine.",
    category: getRandomCategory(),
    isVisible: true,
  },
  {
    foodId: "6",
    name: "Chicken Biryani",
    amount: 13.99,
    image: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQ-9d5A_fMlTMv21U_pgVDpYbJG0I1Pc_rz6Q9XiehBW4VeY0cEKk5D9PDlqfE5PjgngqxdsgjI5iunlKo0EvBiQOPhMaNyHmYYckKAj5LSOA",
    description: "Aromatic basmati rice cooked with tender chicken and spices.",
    category: getRandomCategory(),
    isVisible: false,
  },
  {
    foodId: "7",
    name: "Paneer Butter Masala",
    amount: 11.99,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS59T8yjCsK3lJnDKDjQkVx8z1048ziUNTOCw&s",
    description: "Soft paneer cubes in a creamy tomato-based gravy.",
    category: getRandomCategory(),
    isVisible: true,
  },
  {
    foodId: "8",
    name: "Tacos",
    amount: 9.99,
    image: "https://familiakitchen.com/wp-content/uploads/2021/01/iStock-960337396-3beef-barbacoa-tacos-e1695391119564.jpg",
    description: "Mexican tacos with flavorful fillings wrapped in soft tortillas.",
    category: getRandomCategory(),
    isVisible: true,
  },
  {
    foodId: "9",
    name: "Sushi Platter",
    amount: 15.99,
    image: "https://plazacatering.co.in/blog/wp-content/uploads/2024/07/Untitled-design-55.jpg",
    description: "Assorted sushi rolls with fresh fish, rice, and seaweed.",
    category: getRandomCategory(),
    isVisible: false,
  },
  {
    foodId: "10",
    name: "French Fries",
    amount: 5.49,
    image: "https://www.recipetineats.com/tachyon/2022/09/Crispy-Fries_8.jpg",
    description: "Crispy golden fries served with ketchup or dip.",
    category: getRandomCategory(),
    isVisible: true,
  },
  {
    foodId: "11",
    name: "Cheeseburger",
    amount: 10.49,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlgCo1wH8-gX73JUKqoD_hxfDrK5iv8-OC93UgAy56tn2aAAvcFK5pwPq2rTeTU0QQmtbpfxQs7Vr4SrOF2XDJg--8XSx_QUxYjysC-53bjQ",
    description: "Juicy beef patty topped with melted cheese in a soft bun.",
    category: getRandomCategory(),
    isVisible: true,
  },
  {
    foodId: "12",
    name: "Pancakes",
    amount: 7.49,
    image: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcToT7_-Vqv1eYkhQTUxgL2ARcp-LMFXLsAw5K6uveNBxCSIBuuhAUqMK3idyWQIZVltUdGyYoiE1yIkXftpB_UYJeth8j8i0C0c4y9r6dYX8Q",
    description: "Fluffy pancakes served with maple syrup and butter.",
    category: getRandomCategory(),
    isVisible: true,
  },
  {
    foodId: "13",
    name: "Chocolate Cake",
    amount: 6.99,
    image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRrUVWLx70caUybwXOtJLC9cYoS0aPjR6F2xCN3JqK8ZANJsOLYjG4ceDZjgBKx_b119ce9JyLr86ngNN_s0dfkjrCwPoayTDTHA049QCq5",
    description: "Rich and moist chocolate cake topped with frosting.",
    category: getRandomCategory(),
    isVisible: true,
  },
  {
    foodId: "14",
    name: "Ice Cream Sundae",
    amount: 5.99,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjqupR6WHRGFVAg_G0JMuf-qORfnniB9iCpV80YvWzcKq7eEwPlVS9YDvCiHpG5JfkL8h-HBN7M3CMZc_X6JW7I5P2iWfJeDm74rwOZLC9",
    description: "Ice cream topped with syrup, nuts, and whipped cream.",
    category: getRandomCategory(),
    isVisible: false,
  },
  {
    foodId: "15",
    name: "Veggie Wrap",
    amount: 8.49,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTldaCLx1gDzWPiC9C7eMs8OBGhc8zh_cmwcA&s",
    description: "Healthy wrap filled with fresh veggies and sauces.",
    category: getRandomCategory(),
    isVisible: false,
  },
  {
    foodId: "16",
    name: "Falafel Bowl",
    amount: 9.99,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrwAbn0VyT9W0UAmCvAxzn7EjrnDGPrmuM6g&s",
    description: "Falafel served with fresh vegetables and hummus.",
    category: getRandomCategory(),
    isVisible: true,
  },
  {
    foodId: "17",
    name: "Ramen Noodles",
    amount: 12.49,
    image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcR6mq7iMuu4ZIERgYEA9Rfc7WnqswhySB4lAZCLOrmuGTcDJ3dUSI_U5Efg18P3YWAqTfd1HIRxw4xAP46Hvvij3xWGsLu62nelDiZk0ulF",
    description: "Japanese-style noodles in a flavorful broth with toppings.",
    category: getRandomCategory(),
    isVisible: false,
  },
  {
    foodId: "18",
    name: "Steak",
    amount: 18.99,
    image: "https://justcook.butcherbox.com/wp-content/uploads/2019/11/Perfect-Pan-Seared-Ribeye-Steak.jpg",
    description: "Juicy grilled steak cooked to perfection.",
    category: getRandomCategory(),
    isVisible: true,
  },
  {
    foodId: "19",
    name: "Butter Naan",
    amount: 3.99,
    image: "https://foodess.com/wp-content/uploads/2023/02/Butter-Naan-3-500x500.jpg",
    description: "Soft Indian flatbread brushed with butter.",
    category: getRandomCategory(),
    isVisible: true,
  },
  {
    foodId: "20",
    name: "Momos",
    amount: 8.49,
    image: "https://butfirstchai.com/wp-content/uploads/2022/08/beef-momos-recipe.jpg",
    description: "Steamed dumplings filled with vegetables or meat.",
    category: getRandomCategory(),
    isVisible: true,
  },
  {
    foodId: "21",
    name: "Chole Bhature",
    amount: 10.99,
    image: "https://cdn.uengage.io/uploads/28289/image-14DG1B-1723180624.jpg",
    description: "Spicy chickpeas served with fried bhature bread.",
    category: getRandomCategory(),
    isVisible: false,
  },
  {
    foodId: "22",
    name: "Masala Dosa",
    amount: 9.49,
    image: "https://palatesdesire.com/wp-content/uploads/2022/09/Mysore-masala-dosa-recipe@palates-desire.jpg",
    description: "Crispy dosa stuffed with spiced mashed potatoes.",
    category: getRandomCategory(),
    isVisible: true,
  },
  {
    foodId: "23",
    name: "Idli Sambar",
    amount: 7.49,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSL-AxOFlBX7X829XcyolbnN5KS-l_HiTJUIcEzln9hXifg8kIxJ7ic0E_4maE-szU0zdPTg1ILJTipxJEl1A8t0i0lWuoG2Owx3MolmQ",
    description: "Soft idlis served with hot and tangy sambar.",
    category: getRandomCategory(),
    isVisible: true,
  },
  {
    foodId: "24",
    name: "Vada Pav",
    amount: 4.99,
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/10/vada-pav-recipe.jpg",
    description: "Mumbai street food with spicy potato patty in a bun.",
    category: getRandomCategory(),
    isVisible: true,
  },
  {
    foodId: "25",
    name: "Pav Bhaji",
    amount: 7.99,
    image: "https://www.cookwithmanali.com/wp-content/uploads/2018/05/Best-Pav-Bhaji-Recipe.jpg",
    description: "Mashed vegetable curry served with buttered pav.",
    category: getRandomCategory(),
    isVisible: false,
  },
  {
    foodId: "26",
    name: "Butter Chicken",
    amount: 12.99,
    image: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTWDOOa02Rlo6WMO5SL9Sns07St6KmNaGdGBpT1RZQpGIN5AaSnJCuaUwxutDUSf6jbeWdY7EQrGygyT-ssKTg72m_H6nZeDOq5Sdyn8w",
    description: "Tender chicken cooked in a creamy tomato gravy.",
    category: getRandomCategory(),
    isVisible: false,
  },
  {
    foodId: "27",
    name: "Chicken Shawarma",
    amount: 9.99,
    image: "https://foxeslovelemons.com/wp-content/uploads/2023/06/Chicken-Shawarma-8-500x500.jpg",
    description: "Middle Eastern wrap filled with spiced chicken and veggies.",
    category: getRandomCategory(),
    isVisible: false,
  },
  {
    foodId: "28",
    name: "Hummus with Pita",
    amount: 6.99,
    image: "https://plantbaes.com/wp-content/uploads/2025/03/Hummus-Pita-Bowl-7.jpg",
    description: "Creamy hummus served with soft pita bread.",
    category: getRandomCategory(),
    isVisible: true,
  },
  {
    foodId: "29",
    name: "Kebab Platter",
    amount: 13.49,
    image: "https://www.shutterstock.com/image-photo/assorted-mix-grills-chicken-tikka-600w-2290851499.jpg",
    description: "Assorted grilled kebabs served with dips.",
    category: getRandomCategory(),
    isVisible: true,
  },
  {
    foodId: "30",
    name: "Burrito",
    amount: 9.49,
    image: "https://upload.wikimedia.org/wikipedia/commons/6/60/Burrito.JPG",
    description: "Large Mexican wrap stuffed with rice, beans, and fillings.",
    category: getRandomCategory(),
    isVisible: true,
  }
];
